### ISSUE TITLE
按照步骤来，生成的json数据，但是提示 “To generate device auth, please provide an exchange code for the email: device_id :”

### ISSUE THREAD

**Issue by HelloWorldBest** [MCSeekeri/Epicgame-Action#1]
[https://raw.githubusercontent.com/HelloWorldBest/Epicgame-Action/master/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202021-07-22%20133106.jpg](url)

 2021-07-22 | 08:19:04.876 | INFO  | Found 2 unclaimed freebie(s) for device_id
To generate device auth, please provide an exchange code for the email: device_id :

**Comment by GDWGH** [comment]
不是复制DeviceAuthGenerator窗口里的文字 是复制device_auths.json里的文字

**Comment by MCSeekeri** [comment]
哇我这项目还有人帮我义务解答,感动（
